### PR TITLE
Fix int/guint comparison warnings

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
(for reference -- these warnings are raised when not using the fakeglib header)

**Comment by evanmiller** [comment]
Thanks. Probably a better solution would be making the fakeglib `len` field unsigned (to be compatible with GLib), then fixing the warnings.

https://developer.gnome.org/glib/stable/glib-Pointer-Arrays.html#GPtrArray

**Comment by nyalldawson** [comment]
@evanmiller

Didn't I already do that here?

**Comment by evanmiller** [comment]
Yes of course – sorry, I haven't had my coffee yet!

**Pull request merged**
