### PR TITLE
Add cmake configuration (WIP)

### PR DESCRIPTION
**Pull request by nyalldawson**
TODO:
- Fix odbc library
- install bash completion
- Fix mdb-ver utility

### CODE REVIEW

**Comment by evanmiller** [comment]
Also be sure to update the Travis and Appveyor configs to use the CMake workflow. That may identify additional platform issues.

**Comment by nyalldawson** [comment]
@evanmiller I was originally thinking of just adding this as a beta thing in parallel to the official automake configuration. 

But that said -- I'd also like to experiment with adding some python based tests using ctest (basically running through the test datasets with filters covering every feature, with index supported enabled and disabled), which obviously would need to run on the ci to...

**Comment by evanmiller** [comment]
I'm generally against multiple build systems in a project because one or the other inevitably falls into disrepair. So if you'd like to replace autotools we can have that discussion, but I'd prefer to keep "beta parallel" stuff out of the main tree.

A real test suite would be welcome. Another possible strategy is adding a SQLite exporter / converter and then testing queries over ODBC against both files. We might also explore adding code coverage tools e.g. Coveralls.

**Comment by evanmiller** [comment]
I'm going to close this pull request, and will soon archive this fork now that I have access to the main repository. Feel free to open a new pull request over there if you are still interested in this.

**Pull request closed without merging**
