### PR TITLE
Fix for variable-length fields using SQLGetData

### PR DESCRIPTION
**Pull request by evanmiller**
See:

brianb/mdbtools#130
brianb/mdbtools#131
evanmiller/mdbtools#6

### CODE REVIEW

**Comment by nyalldawson** [comment]
@evanmiller I had no luck directly with this change, but if I add https://github.com/nyalldawson/mdbtools/commit/54c278b25d7d7ac4bbca432a91324e31356767f8 on top then it works correctly.

**Comment by evanmiller** [comment]
I'm concerned about the NUL termination in your patch. The docs state:

> To retrieve data from a column in parts, the application calls SQLGetData multiple times in succession for the same column. On each call, SQLGetData returns the next part of the data. It is up to the application to reassemble the parts, **taking care to remove the null-termination character from intermediate parts of character data.**

So each chunk should be NUL-terminated. I think there's some confusion (in all the patches) about whether `len` should include the termination character.

**Comment by evanmiller** [comment]
See if the updated code works any better for you.

**Comment by evanmiller** [comment]
I'm going to go ahead and merge this. If there are bugs in the merged code, please open a new issue.

**Comment by nyalldawson** [comment]
@evanmiller 

Sorry to resurrect this, but I'm wondering if we misinterpreted this:

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function?view=sql-server-ver15

> SQLGetData can be used to retrieve data from a column that contains variable-length data in parts - that is, when the identifier of the SQL data type of the column is SQL_CHAR, SQL_VARCHAR, SQL_LONGVARCHAR, SQL_WCHAR, SQL_WVARCHAR, SQL_WLONGVARCHAR, SQL_BINARY, SQL_VARBINARY, SQL_LONGVARBINARY, or a driver-specific identifier for a variable-length type.

> To retrieve data from a column in parts, the application calls SQLGetData multiple times in succession for the same column. On each call, SQLGetData returns the next part of the data. It is up to the application to reassemble the parts, taking care to remove the null-termination character from intermediate parts of character data.

Could it be possible that when the docs state "from intermediate parts of character data", it refers ONLY to the SQL*CHAR types and not the SQL_*BINARY types?

**Comment by evanmiller** [comment]
@nyalldawson 

Yes it's possible that OLE and CHAR types should have separate code paths to deal with the NUL terminator. The docs also state:

> The driver uses BufferLength to avoid writing past the end of the *TargetValuePtr buffer when returning variable-length data, such as **character or binary data**. Note that the driver counts the null-termination character when returning **character data** to *TargetValuePtr. *TargetValuePtr must therefore contain space for the null-termination character, or the driver will truncate the data.

This would support the idea that binary data should not make room for a null terminator.

**Comment by nyalldawson** [comment]
@evanmiller

Here's another piece of evidence which indicates binary fields shouldn't be terminated: https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/odbc/src/tpc/db2z_fngetdata.html

"The buffer that the rgbValue argument specifies contains nul-terminated values, unless you retrieve binary data, or the SQL data type of the column is graphic (DBCS) and the C buffer type is SQL_C_CHAR. "

**Comment by evanmiller** [comment]
Feel free to open a PR, otherwise I'll take a closer look this weekend.

**Pull request merged**
