### PR TITLE
Make SQL parser/lexer reentrant

### PR DESCRIPTION
**Pull request by nyalldawson**
Provides thread safety for mdbtools ODBC driver

### CODE REVIEW

**Comment by evanmiller** [comment]
It looks like older versions of bison are choking on `%define api.pure`. I'm fine requiring a newer version of Bison, but this should be checked somehow at configure-time to prevent build errors.

The Mac build can probably be fixed by adding "bison" to the Homebrew package list in `.travis.yml`. I'm not sure about the Appveyor build.

**Comment by nyalldawson** [comment]
Sorry -- I've hit a bit of a brick wall here. My autotools skills aren't sufficient to resolve the errors I'm seeing here!

**Comment by evanmiller** [comment]
No worries – I'll take a crack at it later today. The build log shows

```
==> Pouring bison-3.5.4.catalina.bottle.tar.gz
==> Caveats
bison is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have bison first in your PATH run:
   echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc

For compilers to find bison you may need to set:
  export LDFLAGS="-L/usr/local/opt/bison/lib"
```

So Mac likely also needs the PATH properly set in the Travis config. I have an idea about the Appveyor failure.

If you're otherwise happy with the PR I'l merge it and deal with the build errors later.

**Comment by nyalldawson** [comment]
I think apart from the configure stuff it's good to go. I've stress tested it a lot, and there's no more crashes when multithreading. Valgrind is clean too. Thanks for your assistance with this!

**Comment by evanmiller** [comment]
Sounds good, I'll see if my fixes worked. It will probably still be broken on "regular Joe" macOS installations as the standard Bison even on Catalina is 2.3. So that will give me something to do this week :-)

**Pull request merged**
